spring:
  application:
    name: kafka_consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notificationGroup
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: iwillwin2211@gmail.com
    password: dfeo qioo kogs ytnw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false